### ISSUE TITLE
Release of a first version

### ISSUE THREAD

**Issue by FSharpCSharp** [sigsep/open-unmix-tensorflow#1]
TensorFlow 2.0 is now officially released and also marked as stable. For this reason I wanted to inquire, until when a first release is planned here. There don't seem to be many differences between the pre-releases and the now released final version.

**Comment by faroit** [comment]
thanks for your interest. We are going to use `tf.io` to decode the mp4 stems conveniently on the fly. Therefore we would need to wait a bit longer tf.io will be tested against the tf 2.0 stable [see here](https://github.com/tensorflow/io/issues/517). I am fine with sharing our beta version next week, though.

**Comment by FSharpCSharp** [comment]
Sounds great! I'm looking forward to it!

**Comment by FSharpCSharp** [comment]
I'm sorry to have to come back to this point. Meanwhile the week mentioned above is already over, and unfortunately there is still no release. Is there already a new date for a first release? I can hardly wait.

**Comment by mstfc** [comment]
Looking forward to seeing the beta release!

**Comment by faroit** [comment]
Thanks for you interest.

Since the release of [open-unmix](https://open.unmix.app) in September 2019, the source separation landscape has evolved regarding pre-trained models.

Open-unmix was designed as a baseline to make it easier to do source separation research. Now, spleeter has been made available and got much popularity since its release. We believe it is a good implementation for users to apply source separation in a signal processing pipeline.

For this reason, we decided to __not release the tensorflow implementation of open-unmix publicly__, but rather to make it available for commercial applications.

We continue to improve and update the [PyTorch release](https://github.com/sigsep/open-unmix-pytorch) and we believe that in terms of academic research, this follows the current trend in the community to vastly favor this framework.
